title: APM Alarms
url: https://aialuke.github.io
baseurl: /apm-alarms
markdown: kramdown
permalink: pretty

collections:
  instructions:
    output: false

exclude:
  - Gemfile
  - Gemfile.lock
  - script
  - vendor
  - README.md
  - PRODUCT.md
  - docs
  - .cursor
  - .github
  - .impeccable
